########################################### ################
device: [0]
precision: 16

logging: 
  path: './logs/synthesis'

dataset:
  name: 'Middlebury'

  path: '../data/datasets/Middlebury'
  subset: 'trainingH'  # 'kitti/kitti2012/kitti2015'_'train'/'test'
  val_split: True
  train_aug:

    th: 288
    tw: 576

    horizontal_flip: True
    RandomShiftRotate: True
    RGBShiftStereo: True
    GaussNoiseStereo: True
    RandomBrightnessContrastStereo: True

    # Color aug following "Learning stereo from single images. Watson et al. ECCV2020"
    aug_color: False
    aug_color_brightness: 0.2
    aug_color_contrast: 0.2
    aug_color_saturation: 0.2
    aug_color_hue: 0.01

    aug_zoom: False
    aug_zoom_presets: null
    aug_zoom_use_sr: True
    aug_zoom_min_zoom_ratio: 0.8
    aug_zoom_max_zoom_ratio: 1.5
    aug_zoom_model_path: 'logs/sr/Real-ESRGAN/RealESRGAN_x2plus.pth'
    aug_zoom_half_precision: True
    
    aug_baseline: True
    aug_baseline_presets: null
    aug_baseline_min_baseline_ratio: 0.4
    aug_baseline_max_baseline_ratio: 1.0

    aug_baseline_generated: False
    aug_baseline_generated_nn: False

    max_disparity: 192

training:
  load_path: null  # 'SceneFlow/version_1/checkpoints/last.ckpt'
  save_version: 1

  lr: 0.001
  max_epochs: 300
  milestones: [150, 250]
  gamma: 0.5
  batch_size: 4
  num_workers: 16
  swa: True
  training_scales_weighting: [1, 0.3]

