########################################### ################
device: [0]
precision: 16

###########################################################
model:
  name: 'PSMNet'

  stereo:
    name: 'PSMNet'
    max_disparity: 192
    backbone: 
      type: 'mobilenetv2_100'
      from_scratch: False
      cfg_path: './configs/backbone.yaml'

    corr_volume: False
    gce: False
    multiple_gce: False
    
    regression:
      top_k: 192

###########################################################
logging: 
  path: './logs/stereo'

training:
  load_path: 'SceneFlow/version_1/checkpoints/last.ckpt'
  save_version: 1

  lr: 0.001
  max_epochs: 800
  milestones: [30, 50, 300]
  gamma: 0.5
  batch_size: 8
  num_workers: 8
  swa: True
  training_scales_weighting: [1, 0.3]

testing:
  save_disp_imgs: True
  save_disp_mode: 'plasma'  # 'kitti'/'jet'/'plasma'
  compute_metrics: True
  gt_available: True
