########################################### ################
device: [0, 1]
precision: 16

###########################################################
model:
  name: 'CVPR22'

  stereo:
    name: 'CVPR22'
    min_disparity: 0  # 
    max_disparity: &d 192

    gce: true

    downscale: 1
    pad: 128

    backbone: 
      type: 'mobilenetv2_100'
      from_scratch: False
      cfg_path: './configs/backbone.yaml'
      loftr: false
      dilated_mode: true
    hr_chans: [32, 48, 64]
    conv3d: True
    head: 4
    spp: False

    aggregation_channels: [32, 64, 64, 64]
    # aggregation_channels: [8, 16, 32, 64]
    # aggregation_channels: [4, 8, 16, 32]
    train_init_ratio: 0.5
    rand_init: False
    
    shared_backbone: True
    corr_precompute: false
    corr_levels: 4
    corr_radius: 4
    n_downsample: 2
    slow_fast_gru: True
    fmap_dim: 128
    n_gru_layers: 3
    hidden_dims: [128, 128, 128]

    mixed_precision: True

    # DEQ
    hyper: False
    wnorm: True
    f_solver: 'Anderson'
    b_solver: 'Anderson'
    f_thres: 12
    b_thres: 12
    stop_mode: 'abs'
    eval_factor: 1

    sliced_core: False
    ift: False
    safe_ift: False
    n_losses: 1
    indexing: []
    sup_all: False
    phantom_grad: [1]
    tau: 1.

    sradius_mode: False

    pos_enc: True
    low_mem: True

###########################################################
logging: 
  path: './logs/stereo'

training:
  load_path: null  # 'SceneFlow/version_1/checkpoints/last.ckpt'
  save_version: 1

  thresh_disp: true

  lr: 0.001
  max_epochs: 15
  milestones: []
  gamma: 0.1
  batch_size: 2
  num_workers: 4
  swa: False
  # training_scales_weighting: [1, 0.31, 0.35, 0.39, 0.43, 0.48, 0.53, 0.59, 0.66, 0.73, 0.81, 0.9, 1]
  # training_scales_weighting: [0.3, 0.45, 0.55, 0.9, 1]
  training_scales_weighting: [0.55, 1]
  # training_scales_weighting: [0.3, 0.45, 0.65, 1]
  # training_scales_weighting: [0.3, 1]
  # training_scales_weighting: [0.3, 0.45, 0.5, 0.7, 0.75, 1, 1.1]

testing:
  save_disp_imgs: True
  save_disp_mode: 'plasma'  # 'kitti'/'jet'/'plasma'
  compute_metrics: True
  gt_available: True
