########################################### ################
device: [0, 1]
precision: 16

###########################################################
model:
  name: 'LEAStereo'
  
  stereo:
    name: 'LEAStereo'
    min_disparity: 0  # 
    max_disparity: 192

    fea_num_layers: 6
    mat_num_layers: 12

    fea_filter_multiplier: 8
    fea_block_multiplier: 4
    fea_step: 3

    mat_filter_multiplier: 8
    mat_block_multiplier: 4
    mat_step: 3

    pretrained_path: 'Sceneflow/best/best.pth'

###########################################################
logging: 
  path: './logs/stereo'

training:
  load_path: null  # 'SceneFlow/version_1/checkpoints/last.ckpt'
  save_version: 1

  lr: 0.001
  max_epochs: 5
  milestones: [3]
  gamma: 0.1
  batch_size: 4
  num_workers: 16
  swa: True
  training_scales_weighting: [1]

testing:
  save_disp_imgs: True
  save_disp_mode: 'plasma'  # 'kitti'/'jet'/'plasma'
  compute_metrics: True
  gt_available: True
