########################################### ################
device: [0, 1]
precision: 16

###########################################################
model:
  name: 'DEQRAFTCoEx'

  stereo:
    name: 'DEQRAFTCoEx'
    min_disparity: 0  # 
    max_disparity: &d 512

    downscale: 1
    pad: 128

    backbone: 
      type: 'mobilenetv2_100'
      from_scratch: False
      cfg_path: './configs/backbone.yaml'
    conv3d: True

    aggregation_channels: [8,16,32,64]
    init_disp: True
    
    shared_backbone: False
    corr_implementation: 'reg'
    corr_levels: 4
    corr_radius: 4
    n_downsample: 3
    slow_fast_gru: True
    n_gru_layers: 3
    fmap_dim: 32
    hidden_dims: [32, 32, 32]

    mixed_precision: True

    # DEQ
    hyper: True
    wnorm: True
    f_solver: 'Anderson'
    b_solver: 'Anderson'
    f_thres: 36
    b_thres: 36
    stop_mode: 'abs'
    eval_factor: .12

    sliced_core: False
    ift: False
    safe_ift: False
    n_losses: 2
    indexing: []
    sup_all: False
    phantom_grad: [2]
    tau: 1.

    sradius_mode: False

###########################################################
logging: 
  path: './logs/stereo'

training:
  load_path: null  # 'SceneFlow/version_1/checkpoints/last.ckpt'
  save_version: 1

  thresh_disp: False

  lr: 0.001
  max_epochs: 15
  milestones: []
  gamma: 0.1
  batch_size: 2
  num_workers: 4
  swa: False
  training_scales_weighting: [0.3, 0.45, 0.55, 0.9, 1]

testing:
  save_disp_imgs: True
  save_disp_mode: 'argoverse'  # 'kitti'/'jet'/'plasma'
  compute_metrics: True
  gt_available: True
