name: 'CARLA'

path: '../data/datasets/Stereo_CARLA_Dataset'
subset: 'train_K-kitti_b-05'  
  # 'train'/'test'_'K-kitti'/'K-driving'/'K-all'_'b-02'/'b-05'/'b-10'/'b-all'
val_split: True
train_aug:

  th: 320
  tw: 608

  horizontal_flip: True
  RandomShiftRotate: True
  RGBShiftStereo: True
  GaussNoiseStereo: True
  RandomBrightnessContrastStereo: True

  # Color aug following "Learning stereo from single images. Watson et al. ECCV2020"
  aug_color: True
  aug_color_brightness: 0.2
  aug_color_contrast: 0.2
  aug_color_saturation: 0.2
  aug_color_hue: 0.01

  aug_zoom: False
  aug_zoom_use_sr: True
  aug_zoom_model_path: 'logs/sr/Real-ESRGAN/RealESRGAN_x2plus.pth'
  aug_zoom_half_precision: True

  aug_baseline: False