########################################### ################
device: [0, 1]
precision: 16

###########################################################
model:
  name: 'CFNet'

  stereo:
    name: 'CFNetReLU'
    min_disparity: 0  # 
    max_disparity: 256

    use_concat_volume: True

###########################################################
logging: 
  path: './logs/stereo'

training:
  load_path: null  # 'SceneFlow/version_1/checkpoints/last.ckpt'
  save_version: 1

  lr: 0.001
  max_epochs: 10
  milestones: []
  gamma: 0.5
  batch_size: 2
  num_workers: 4
  swa: False
  training_scales_weighting: [0.25, 0.35, 0.5, 0.5, 0.7, 1.0, 1, 1.4, 2]

testing:
  save_disp_imgs: True
  save_disp_mode: 'plasma'  # 'kitti'/'jet'/'plasma'
  compute_metrics: True
  gt_available: True
