########################################### ################
device: [0, 1]
precision: 32

###########################################################
model:
  name: 'DSMNet'
  
  stereo:
    name: 'DSMNet'
    min_disparity: 0  # 
    max_disparity: 192

###########################################################
logging: 
  path: './logs/stereo'

training:
  load_path: null  # 'SceneFlow/version_1/checkpoints/last.ckpt'
  save_version: 1

  lr: 0.001
  max_epochs: 10
  milestones: [7]
  gamma: 0.1
  batch_size: 2
  num_workers: 16
  swa: False
  training_scales_weighting: [0.2, 0.6, 1.0]

testing:
  save_disp_imgs: True
  save_disp_mode: 'plasma'  # 'kitti'/'jet'/'plasma'
  compute_metrics: True
  gt_available: True
