########################################### ################
device: [0, 1]
precision: 16

###########################################################
model:
  name: 'CREStereo'

  stereo:
    name: 'CREStereo'
    
    min_disparity: 0
    max_disparity: &d 192
    mixed_precision: true

    iters: 10

###########################################################
logging: 
  path: './logs/stereo'

training:
  load_path: null  # 'SceneFlow/version_1/checkpoints/last.ckpt'
  save_version: 1

  thresh_disp: False

  lr: 0.001
  max_epochs: 15
  milestones: []
  gamma: 0.1
  batch_size: 2
  num_workers: 4
  swa: False
  
  training_scales_weighting: 'cre'

testing:
  save_disp_imgs: True
  save_disp_mode: 'plasma'  # 'kitti'/'jet'/'plasma'
  compute_metrics: True
  gt_available: True
