########################################### ################
device: [0, 1]
precision: 32

###########################################################
model:
  name: 'RAFTStereo'

  stereo:
    name: 'RAFTStereo'
    min_disparity: 0  # 
    max_disparity: 192

    train_iters: 16
    valid_iters: 32
    
    corr_implementation: 'reg'
    shared_backbone: False
    corr_levels: 4
    corr_radius: 4
    n_downsample: 2
    slow_fast_gru: False
    n_gru_layers: 3
    hidden_dims: [128, 128, 128]

    # train_iters: 7
    # valid_iters: 7
    
    # corr_implementation: 'reg_cuda'
    # shared_backbone: True
    # corr_levels: 4
    # corr_radius: 4
    # n_downsample: 3
    # slow_fast_gru: True
    # n_gru_layers: 2
    # hidden_dims: [128, 128, 128]

###########################################################
logging: 
  path: './logs/stereo'

training:
  load_path: null  # 'SceneFlow/version_1/checkpoints/last.ckpt'
  save_version: 1

  lr: 0.001
  max_epochs: 15
  milestones: []
  gamma: 0.1
  batch_size: 2
  num_workers: 4
  swa: False
  training_scales_weighting: 'raft'

testing:
  save_disp_imgs: True
  save_disp_mode: 'plasma'  # 'kitti'/'jet'/'plasma'
  compute_metrics: True
  gt_available: True
